# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/arty/Documents/GitHub/LDPC/ip_core/ip_core.srcs/sources_1/ip/ldpc_0/ldpc_0.xci
# IP: The module: 'ldpc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arty/Documents/GitHub/LDPC/ip_core/ip_core.gen/sources_1/ip/ldpc_0/ldpc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ldpc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/arty/Documents/GitHub/LDPC/ip_core/ip_core.srcs/sources_1/ip/ldpc_0/ldpc_0.xci
# IP: The module: 'ldpc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arty/Documents/GitHub/LDPC/ip_core/ip_core.gen/sources_1/ip/ldpc_0/ldpc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ldpc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
