n: 1120
k: 840
p: 56
sm_array:
  - { row: 0, col: 0, shift: 5 }
  - { row: 0, col: 1, shift: 14 }
  - { row: 0, col: 2, shift: 12 }
  - { row: 0, col: 3, shift: 1 }
  - { row: 0, col: 4, shift: 2 }
  - { row: 0, col: 5, shift: 37 }
  - { row: 0, col: 6, shift: 45 }
  - { row: 0, col: 7, shift: 26 }
  - { row: 0, col: 8, shift: 24 }
  - { row: 0, col: 9, shift: 0 }
  - { row: 0, col: 10, shift: 3 }
  - { row: 0, col: 12, shift: 34 }
  - { row: 0, col: 13, shift: 7 }
  - { row: 0, col: 14, shift: 46 }
  - { row: 0, col: 15, shift: 10 }
  - { row: 1, col: 0, shift: 0 }
  - { row: 1, col: 1, shift: 35 }
  - { row: 1, col: 2, shift: 1 }
  - { row: 1, col: 3, shift: 26 }
  - { row: 1, col: 4, shift: 0 }
  - { row: 1, col: 5, shift: 10 }
  - { row: 1, col: 6, shift: 16 }
  - { row: 1, col: 7, shift: 16 }
  - { row: 1, col: 8, shift: 34 }
  - { row: 1, col: 9, shift: 4 }
  - { row: 1, col: 10, shift: 2 }
  - { row: 1, col: 11, shift: 23 }
  - { row: 1, col: 12, shift: 0 }
  - { row: 1, col: 13, shift: 51 }
  - { row: 1, col: 15, shift: 49 }
  - { row: 1, col: 16, shift: 20 }
  - { row: 2, col: 0, shift: 12 }
  - { row: 2, col: 1, shift: 28 }
  - { row: 2, col: 2, shift: 22 }
  - { row: 2, col: 3, shift: 46 }
  - { row: 2, col: 4, shift: 3 }
  - { row: 2, col: 5, shift: 16 }
  - { row: 2, col: 6, shift: 51 }
  - { row: 2, col: 7, shift: 2 }
  - { row: 2, col: 8, shift: 25 }
  - { row: 2, col: 9, shift: 29 }
  - { row: 2, col: 10, shift: 19 }
  - { row: 2, col: 11, shift: 18 }
  - { row: 2, col: 12, shift: 52 }
  - { row: 2, col: 14, shift: 37 }
  - { row: 2, col: 16, shift: 34 }
  - { row: 2, col: 17, shift: 39 }
  - { row: 3, col: 0, shift: 0 }
  - { row: 3, col: 1, shift: 51 }
  - { row: 3, col: 2, shift: 16 }
  - { row: 3, col: 3, shift: 31 }
  - { row: 3, col: 4, shift: 13 }
  - { row: 3, col: 5, shift: 39 }
  - { row: 3, col: 6, shift: 27 }
  - { row: 3, col: 7, shift: 33 }
  - { row: 3, col: 8, shift: 8 }
  - { row: 3, col: 9, shift: 27 }
  - { row: 3, col: 10, shift: 53 }
  - { row: 3, col: 11, shift: 13 }
  - { row: 3, col: 13, shift: 52 }
  - { row: 3, col: 14, shift: 33 }
  - { row: 3, col: 17, shift: 38 }
  - { row: 3, col: 18, shift: 7 }
  - { row: 4, col: 0, shift: 36 }
  - { row: 4, col: 1, shift: 6 }
  - { row: 4, col: 2, shift: 3 }
  - { row: 4, col: 3, shift: 51 }
  - { row: 4, col: 4, shift: 4 }
  - { row: 4, col: 5, shift: 19 }
  - { row: 4, col: 6, shift: 4 }
  - { row: 4, col: 7, shift: 45 }
  - { row: 4, col: 8, shift: 48 }
  - { row: 4, col: 9, shift: 9 }
  - { row: 4, col: 11, shift: 11 }
  - { row: 4, col: 12, shift: 22 }
  - { row: 4, col: 13, shift: 23 }
  - { row: 4, col: 14, shift: 43 }
  - { row: 4, col: 18, shift: 14 }
  - { row: 4, col: 19, shift: 1 }
no_final_parity: false
